language: python
sudo: false
python:
- '3.4'
env:
- DJANGO_VERSION=1.8
- DJANGO_VERSION=1.9
- DJANGO_VERSION=1.10
install:
- pip install -r test-requirements.txt
- pip install -U django==$DJANGO_VERSION
script: ./runtests
repo: dabapps/csv-wrangler
