language: python
sudo: false
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"
env:
- DJANGO_VERSION=1.11
- DJANGO_VERSION=2.2
install:
- pip install -r test-requirements.txt
- pip install -U django~=$DJANGO_VERSION
script: ./runtests
repo: dabapps/csv-wrangler
